### ISSUE TITLE
Add player value tracking

### ISSUE THREAD

**Issue by davilimap** [slyjeff/ArkhamOverlay#6]
Add UI to display player health, sanity. Add UI to raise and lower each player's values.

Consider adding clues and resources.

**Comment by slyjeff** [comment]
I see two "modes" for displaying these. One is putting info in the four courners of the screen at all times- another would be to show it bigger one at a time that can be toggled on an off, perhaps in conjunction with showing a player's hand. IN this case you scould show the investigator card. Might be cool to toggle on when a player is taking his/her turn, or maybe drawing in the Mythos.
